<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use ZipArchive;

class ExportController extends Controller
{
    public function downloadZip($modelName)
{
    $zip = new \ZipArchive;
    // Pastikan kita punya versi Tunggal dan Jamak yang benar
    $singularName = \Illuminate\Support\Str::singular($modelName); 
    $pluralPath = strtolower(\Illuminate\Support\Str::plural($modelName));
    
    $fileName = $singularName . '_Module.zip';

    if ($zip->open(public_path($fileName), \ZipArchive::CREATE | \ZipArchive::OVERWRITE) === TRUE) {
        
        // 1. Ambil Controller (Gunakan Nama Tunggal: BakeryController)
        $controllerPath = app_path("Http/Controllers/{$singularName}Controller.php");
        if (File::exists($controllerPath)) {
            $zip->addFile($controllerPath, "Controllers/{$singularName}Controller.php");
        }

        // 2. Ambil Model (Gunakan Nama Tunggal: Bakery)
        $modelPath = app_path("Models/{$singularName}.php");
        if (File::exists($modelPath)) {
            $zip->addFile($modelPath, "Models/{$singularName}.php");
        }

        // 3. Ambil Folder Views (Gunakan Nama Jamak: bakeries)
        $viewPath = resource_path("views/{$pluralPath}");
        if (File::exists($viewPath)) {
            $files = File::allFiles($viewPath);
            foreach ($files as $file) {
                $zip->addFile($file->getRealPath(), "Views/{$pluralPath}/" . $file->getFilename());
            }
        }

        // 4. Cari Migration (Gunakan Nama Jamak: create_bakeries_table)
        $migrationFiles = File::files(database_path('migrations'));
        foreach ($migrationFiles as $file) {
            if (str_contains($file->getFilename(), "create_{$pluralPath}_table")) {
                $zip->addFile($file->getRealPath(), "Migrations/" . $file->getFilename());
            }
        }

        // 5. Buat Instruksi README secara otomatis
        $routeCode = "Route::resource('{$pluralPath}', \\App\\Http\\Controllers\\{$singularName}Controller::class);";
        
        $readmeContent = "--- MODUL GENERATED BY AVW STORE ---\n\n";
        $readmeContent .= "Modul: {$singularName}\n";
        $readmeContent .= "Tanggal Generate: " . date('Y-m-d H:i:s') . "\n\n";
        $readmeContent .= "PANDUAN INSTALASI:\n";
        $readmeContent .= "1. Copy file-file di dalam ZIP ini ke folder Laravel Anda sesuai strukturnya.\n";
        $readmeContent .= "2. Buka file routes/web.php dan tambahkan baris berikut:\n\n";
        $readmeContent .= "   {$routeCode}\n\n";
        $readmeContent .= "3. Jalankan perintah 'php artisan migrate' di terminal Anda.\n";
        $readmeContent .= "4. Akses modul di browser melalui alamat: /{$pluralPath}\n\n";
        $readmeContent .= "Terima kasih telah menggunakan AVW Generator!";

        $zip->addFromString("README_CARA_PAKAI.txt", $readmeContent);

        $zip->close();
    }

    return response()->download(public_path($fileName))->deleteFileAfterSend(true);
    }
}
